[workspace]
members = [ "crates/*" ]

[profile.release]
incremental = true
debug = true

[patch.'crates-io']
salsa = { git = "https://github.com/matklad/salsa.git", branch = "transitive-untracked" }
cargo_metadata = { git = "https://github.com/matklad/cargo_metadata.git", branch = "well-typed" }
