[package]
edition = "2018"
name = "ra_hir"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
arrayvec = "0.4.10"
log = "0.4.5"
relative-path = "0.4.0"
salsa = "0.9.0"
rustc-hash = "1.0"
parking_lot = "0.7.0"
id-arena = "2.0"
ena = "0.11"
ra_syntax = { path = "../ra_syntax" }
ra_editor = { path = "../ra_editor" }
ra_db = { path = "../ra_db" }
test_utils = { path = "../test_utils" }
cm = { path = "../cm" }

[dev-dependencies]
flexi_logger = "0.10.0"
